name: Test Github Actions
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: actions/checkout@v2
      - name: Build stl file
        uses: ./
        with:
          scad_file: ioshield.scad
          output_file: ioshield.stl
          options: "-D size1=10 -D size2=100"
      - name: Upload stl file as artifact
        uses: actions/upload-artifact@v2
        with:
          name: built_stl
          path: ioshield.stl
